using System;

namespace Ekko.Library.Responselmpl
{
    public class Read_ProductDto
    {
        public string item_nbr { get; set; }
        public string oitem_nbr { get; set; }
        public string big_key { get; set; }
        public string q_code { get; set; }
        public string item_desc { get; set; }
        public string item_alias { get; set; }
        public string eng_name { get; set; }
        public string rec_un { get; set; }
        public string item_un { get; set; }
        public string sales_un { get; set; }
        public string ud_oh_ctl { get; set; }
        public decimal safety_qty { get; set; }
        public string ware_nbr { get; set; }
        public string item_type { get; set; }
        public string m_type { get; set; }
        public string i_type { get; set; }
        public decimal a_in_qty { get; set; }
        public string ven_nbr { get; set; }
        public string item_nbr1 { get; set; }
        public string pro_nbr { get; set; }
        public decimal mat_qty { get; set; }
        public string mat_un { get; set; }
        public decimal unit_price { get; set; }
        public decimal bot_price { get; set; }
        public string pri_type { get; set; }
        public decimal price_1 { get; set; }
        public decimal price_2 { get; set; }
        public decimal price_3 { get; set; }
        public decimal price_4 { get; set; }
        public decimal price_5 { get; set; }
        public decimal unit_cost { get; set; }
        public decimal matl_cost { get; set; }
        public decimal labor_cost { get; set; }
        public decimal other_cost { get; set; }
        public decimal in_box { get; set; }
        public decimal qty_pbox { get; set; }
        public decimal qty_box { get; set; }
        public decimal qty_xz { get; set; }
        public decimal cj_per { get; set; }
        public decimal cuft { get; set; }
        public decimal n_wight { get; set; }
        public decimal g_wight { get; set; }
        public string pbox_nbr { get; set; }
        public string in_nbr { get; set; }
        public decimal in_qty { get; set; }
        public decimal in_box1 { get; set; }
        public decimal qty_pbox1 { get; set; }
        public decimal cuft1 { get; set; }
        public decimal n_wight1 { get; set; }
        public decimal g_wight1 { get; set; }
        public string pbox_nbr1 { get; set; }
        public string in_nbr1 { get; set; }
        public decimal itm_hours1 { get; set; }
        public decimal itm_hours2 { get; set; }
        public string remark { get; set; }
        public string remark1 { get; set; }
        public decimal oh_qty { get; set; }
        public decimal pur_qty { get; set; }
        public decimal ord_qty { get; set; }
        public decimal sub_qty { get; set; }
        public DateTime? newdate { get; set; }
        public DateTime? l_shpdate { get; set; }
        public DateTime? l_update { get; set; }
        public string image { get; set; }
        public string itemdesc { get; set; }
        public decimal status { get; set; }
        public string shp_desc { get; set; }
        public bool isedit { get; set; }
        public string p_weight { get; set; }
        public decimal cyc_time { get; set; }
        public string item_ctl { get; set; }
        public string cadfile { get; set; }
        public DateTime? l_edtdate { get; set; }
        public DateTime? l_crtdate { get; set; }
        public string sys_type { get; set; }
        public string stock_desc { get; set; }
        public string stock_desc1 { get; set; }
        public string bar_code { get; set; }
        public string bar_code2 { get; set; }
        public DateTime? sdate { get; set; }
        public DateTime? l_recdate { get; set; }
        public decimal last_price { get; set; }
        public decimal l_shppri { get; set; }
        public string last_ven { get; set; }
        public DateTime? crt_date { get; set; }
        public string crt_user { get; set; }
        public string bmp_var { get; set; }
        public string zyc_nbr { get; set; }
        public decimal bas_l { get; set; }
        public decimal bas_w { get; set; }
        public decimal bas_h { get; set; }
        public decimal bas_bz { get; set; }
        public decimal bas_cqs { get; set; }
        public decimal bas_cqz { get; set; }
        public decimal bas_kf { get; set; }
        public decimal bas_dz { get; set; }
        public decimal bas_ldz { get; set; }
        public decimal bas_bb { get; set; }
        public string sku { get; set; }
        public string bas_oly { get; set; }
        public string ebas_oly { get; set; }
        public string zz_remark { get; set; }
        public string car_nbr { get; set; }
        public string year { get; set; }
        public string shp_type { get; set; }
        public string qc_excel { get; set; }
        public string ben { get; set; }
        public string ye { get; set; }
        public DateTime? edit_date { get; set; }
        public string edit_user { get; set; }
        public decimal pro_hours { get; set; }
        public decimal ipro_hours { get; set; }
        public string tranok { get; set; }
        public string tranop { get; set; }
        public decimal trancnt { get; set; }
    }
}